; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs=TFM_100
extra_configs = platformio_override.ini

[env:TFM_100]
platform = atmelavr
framework = arduino
board = TFM_100

; directive for Platformio Inspect, disable for normal builds
; board_upload.maximum_size = 65536
; build_type = debug

lib_deps=
  coryjfowler/mcp_can@^1.5.1
  robtillaart/ANSI
  https://github.com/budulinek/MAX31865_NonBlocking.git

build_flags =
  -I include
  -D J1939_PAYLOAD_POOL_SIZE=100
  -D J1939_MAX_REGISTERED_MESSAGES=10
  -D J1939_MESSAGE_QUEUE=10
  -D DIAGNOSTICS_MEMORY_SIZE=10
  -Os                            ; reduce code size
  -flto                          ; enable Link Time Optimization (further code size reduction)
  -ffunction-sections            ; place each function in a separate section
  -fdata-sections                ; place each variable/data in a separate section
  -Wl,--gc-sections              ; linker: remove unused functions/data
  -lprintf_min                   ; force minimal printf (without float) to reduce flash
  -Wl,-Map=.pio/build/TFM_100/firmware.map  ; generate the .map file with symbols and sizes

monitor_speed=115200
