; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs=TFM_100

[env:TFM_100]
platform = atmelavr
framework = arduino
board = TFM_100

; directive for Platformio Inspect, disable for normal builds
; board_upload.maximum_size = 65536
; build_type = debug

lib_deps=
  coryjfowler/mcp_can@^1.5.1
  robtillaart/ANSI
  https://github.com/budulinek/MAX31865_NonBlocking.git
  https://github.com/BlueAndi/vscp-arduino.git

upload_port=COM17
monitor_port=COM17
build_flags =
  -I include
  -D J1939_PAYLOAD_POOL_SIZE=100
  -D J1939_MAX_REGISTERED_MESSAGES=10
  -D J1939_MESSAGE_QUEUE=10
  -D DIAGNOSTICS_MEMORY_SIZE=10
  -D VSCP_CONFIG_ENABLE_DM=0
  -D VSCP_CONFIG_HEARTBEAT_NODE=0
  -Os                            ; ottimizza per ridurre la dimensione del codice
  -flto                          ; abilita Link Time Optimization (più riduzione codice)
  -ffunction-sections            ; mette ogni funzione in una sezione separata
  -fdata-sections                ; mette ogni variabile/dato in una sezione separata
  -Wl,--gc-sections              ; linker: elimina funzioni/dati non usati
  -lprintf_min                   ; forza printf minimale (senza float) per ridurre la flash
  -Wl,-Map=.pio/build/TFM_100/firmware.map  ; genera il file .map con simboli e dimensioni

monitor_speed=115200
